= How to enable cucumber

This tutorial explains how to add cucumber tests with ApplicationContext for a new module.
As an exmaple take the _artisjaap-properties_ because it is simple module.

== setup

Cucumbers are defined in a separate module. In the module that is tested, there should be no dependencies to cucumber.
As an example take the artisjaap-mail, this module will be tested in a separete module artisjaap-mail-scenarios.

This module should be setup as follows:

in src/test/java/be.artisjaap.<module>.cucumber:

CucumberContext:: This is a configuration file. It should have the following annotations

- @RunWith(Cucumber.class)
- @CucumberOptions(features = "classpath:feature")

<module>InMemoryTestParent:: This is another configuration class. This one is to configure spring boot. It contains the Configuration classes of the spring context

- @ContextConfiguration(classes = {MailApplication.class, PropertiesApplication.class})

<module>StepDefinition:: one or more step definition files that extend the TestParent